# Numpy Exercises

In [12]:
import numpy as np
# Life w/o numpy to life with numpy


## Setup 1


In [13]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

### Exercise 1 -
Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [18]:
sum_of_a = sum(a)
sum_of_a

55

 ### Exercise 2 - 
 Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [19]:
min_of_a = min(a)
min_of_a

1

### Exercise 3 -
Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [20]:
max_of_a = max(a)
max_of_a

10

### Exercise 4 - 
Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [22]:
mean_of_a = sum_of_a / len(a)
mean_of_a

5.5

### Exercise 5 - 
Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [24]:
product_of_a = 1
for n in a:
    product_of_a = product_of_a * n
   
product_of_a
    

3628800

### Exercise 6 - 
Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [25]:
squares_of_a = [n ** 2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Exercise 7 - 
Make a variable named odds_in_a. It should hold only the odd numbers


In [26]:
odds_in_a =[ n for n in a if n % 2 != 0 ]
odds_in_a

[1, 3, 5, 7, 9]

### Exercise 8 - 
Make a variable named evens_in_a. It should hold only the evens.

In [27]:
evens_in_a =[ n for n in a if n % 2 == 0 ]
evens_in_a

[2, 4, 6, 8, 10]

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [56]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

### Exercise 1-
refactor the following to use numpy. Use sum_of_b as the variable.

    **Hint, you'll first need to make sure that the "b" variable is a numpy array**



In [30]:
type(b)

list

In [58]:
#we need to convert c which is a list into an array
b = np.array(b)
type(b)
#this gives us the sum of each column. we dont want that
sum_of_b = sum(b)

#this gives us the sum of each row
example = sum(b[0])

#we need a for loop to do the sum in each row
sum_of_b = 0
for row in b:
    sum_of_b = sum_of_b + sum(row)
    # sum_of_b += sum(row)
sum_of_b    



33

### Exercise 2 -
refactor the following to use numpy. 

In [37]:
# using comprehension listb
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [38]:
#other way
if min(b[0]) <= min(b[1]):
    min_of_b = min(b[0])
else:
    min_of_b = min(b[1])
min_of_b

3

### Exercise 3 - 
refactor the following maximum calculation to find the answer with numpy.

In [39]:
#using comprehension list
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

### Exercise 4 - 
refactor the following using numpy to find the mean of b

In [40]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

### Exercise 5 - 
refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [41]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product_of_b

20160

### Exercise 6 - 
refactor the following to use numpy to find the list of squares 

In [43]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b 
type(squares_of_b)

list

### Exercise 7 - 
refactor using numpy to determine the odds_in_b

In [44]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

### Exercise 8 -
refactor the following to use numpy to filter only the even numbers


In [45]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

### Exercise 9 - 
print out the shape of the array b.


In [59]:
print(b.shape)

(2, 3)


### Exercise 10 - 
transpose the array b.

In [60]:
 np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [61]:
b

array([[3, 4, 5],
       [6, 7, 8]])

### Exercise 11 - 
reshape the array b to be a single list of 6 numbers. (1 x 6)

In [64]:
np.reshape(b,6)


array([3, 4, 5, 6, 7, 8])

### Exercise 12 - 
reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [65]:
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [2]:
import numpy as np

In [3]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [4]:
type(c)

list

In [5]:
#we need to convert c which is a list into an array
c = np.array(c)

### Exercise 1 
- Find the min, max, sum, and product of c.

In [8]:
(sum(sum(ct_times_c)))       
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

1

In [37]:
c.max()

9

In [38]:
c.sum()

45

In [40]:
product_of_c = c.prod()
product_of_c

362880

### Exercise 2
 Determine the standard deviation of c.

In [43]:
np.std(c)


2.581988897471611

In [75]:
np.std(c, axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [76]:
np.std(c, axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

### Exercise 3 - 
Determine the variance of c

In [77]:
np.var(c)

6.666666666666667

### Exercise 4 - 
Print out the shape of the array c


In [78]:
print(c.shape)

(3, 3)



### Exercise 5 - 
Transpose c and print out transposed result.



In [79]:
 np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [80]:
print( np.transpose(c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 6 - 
Get the dot product of the array c with c. 



In [81]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - 
Write the code necessary to sum up the result of c times c transposed. Answer should be 261



In [32]:
ct= np.transpose(c)
ct_times_c = ct *c
ct_times_c
sum_ct_times_c = ct_times_c.sum()

sum_ct_times_c

numpy.int64

### Exercise 8 - 
Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [36]:
cxc= c * c
cxc_t = np.transpose(cxc)
prod_cxc_t = cxc_t.prod()
prod_cxc_t

131681894400

## Setup 4


In [44]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [46]:
d =np.array(d)

### Exercise 1 - 
Find the sine of all the numbers in d


In [49]:
sine_d = np.sin(d)
sine_d

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - 
Find the cosine of all the numbers in d



In [51]:
cos_d = np.cos(d)
cos_d

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - 
Find the tangent of all the numbers in d



In [52]:
tan_d = np.tan(d)
tan_d

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - 
Find all the negative numbers in d



In [53]:
neg_num_d = d[d < 0]
neg_num_d

array([-90, -30, -45, -45])

### Exercise 5 - 
Find all the positive numbers in d



In [54]:
pos_num_d = d[d > 0]
pos_num_d

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

### Exercise 6 - 
Return an array of only the unique numbers in d.



In [55]:
unique_d = np.unique(d)
unique_d

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - 
Determine how many unique numbers there are in d.


In [56]:
len(np.unique(d))

11


### Exercise 8 - 
Print out the shape of d.


In [59]:
print(d.shape)

(3, 6)



### Exercise 9 - 
Transpose and then print out the shape of d.


In [60]:
dt =  np.transpose(d)
print(dt.shape)

(6, 3)


### Exercise 10 - 
Reshape d into an array of 9 x 2


In [66]:
new_d = d.reshape(9,2)

In [67]:
print(new_d)

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
